#!/usr/bin/env bash
script=$(basename "$0")
echo "$script: Starting."
"$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)/src/scripts/devspace/setup/set-env-vars.sh"
"$SCRIPTS_ROOT/openssl/generate-root-ca.sh"
"$SCRIPTS_ROOT/argocd/generate-devcerts.sh"
echo "$script: Finished."
