#!/usr/bin/env bash
script="$1"
i="$0"
scriptsRoot="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)/src/scripts"
"$scriptsRoot/devspace/setup/set-env-vars.sh"
echo "$i: Started running: ${script}."
"$scriptsRoot/$script.sh"
echo "$i: Finished running: ${script}."
