#!/usr/bin/env zsh
#shellcheck shell=bash
#shellcheck disable=SC1091
#shellcheck source=src/scripts/setup/set-env-vars.sh
script="$1"
command="$2"
scriptsRoot="$(cd -- "$(dirname -- "${BASH_SOURCE-$0}")" &> /dev/null && pwd)/src/scripts"
source "$scriptsRoot/setup/set-env-vars.sh"
"$KINDEST_ARGO_CD_SCRIPTS_ROOT/$script.sh" "$command"
