# https://kind.sigs.k8s.io/docs/user/configuration/
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: default
# https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
featureGates:
# https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/
runtimeConfig:
networking:
  ipFamily: dual
  apiServerPort: 6443
  kubeProxyMode: iptables
nodes:
- role: control-plane
- role: worker
- role: worker
