spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: ssh://git@github.com:AlephZ-ai/argo-cd-devspace.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
