#!/usr/bin/env bash
script=$(basename "$0")
echo "$script: Starting."
"$(dirname "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)")/src/scripts/devspace/setup/set-env-vars.sh"
pushd "$PROJECT_ROOT" || exit
"$SCRIPTS_ROOT/forward-port.sh" &
argocd version
popd || exit
echo "$script: Finished."
