# https://docs.docker.com/compose/compose-file/
version: '3.8'

services:
  # Kind cluster
  kindest:
    image: "cr.alephz.ai/devcontainers/$KINDEST_ARGO_CD_PROJECT_NAME:latest"
    container_name: $KINDEST_ARGO_CD_PROJECT_NAME-devspace
    labels: ["ai.alephz.role=$KINDEST_ARGO_CD_PROJECT_NAME"]
    env_file: .env
    environment:
      - KINDEST_ARGO_CD_PROJECT_ROOT=/workspaces/$KINDEST_ARGO_CD_PROJECT_NAME
    # https://docs.docker.com/compose/compose-file/build/#build-definition
    # Includes https://github.com/devcontainers/features/tree/main/src/common-utils
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # https://github.com/dotnet/dotnet-docker/tree/main/src/runtime-deps
        IMAGE: debian:latest
    networks:
      - default
    volumes:
      - ../..:/workspaces:cached

networks:
  default:
