version: '3.8'

services:
  # Kind cluster
  k8s:
    # Includes https://github.com/devcontainers/features/tree/main/src/common-utils
    # https://github.com/devcontainers/images/tree/main/src/base-debian
    image: "mcr.microsoft.com/devcontainers/base:bullseye"
    labels: ["ai.alephz.role=K8s Kind Cluster"]
    networks:
      - default
    volumes:
      - ../..:/workspaces:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

networks:
  default:
