apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://argoproj.github.io/argo-helm'
    targetRevision: HEAD
    chart: argo-cd
    helm:
      values: |
        server:
          ingress:
            enabled: "true"
            hosts:
              - argocd.local
            annotations:
              kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    destination:
      server: 'https://kubernetes.default.svc'
      namespace: argocd
    source:
      repoURL: 'https://github.com/AlephZ-ai/kindest-argo-cd.git'
      path: src/argocd
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
