apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  source:
    KINDEST_ARGO_CD_REPO_URL: 'https://argoproj.github.io/argo-helm'
    targetRevision: HEAD
    chart: argo-cd
