apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
source:
  repoURL: 'https://github.com/AlephZ-ai/kindest-argo-cd.git'
  path: src/argocd
destination:
  server: 'https://kubernetes.default.svc'
  namespace: argocd
syncOptions:
  - CreateNamespace=true
  - ServerSideApply=true
  source:
    repoURL: 'https://argoproj.github.io/argo-helm'
    targetRevision: HEAD
    chart: argo-cd
    helm:
      values: |
        server:
          ingress:
            enabled: "true"
            hosts:
              - argocd.local
            annotations:
              kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
project: default
source:
  repoURL: 'https://github.com/AlephZ-ai/kindest-argo-cd.git'
  path: src/argocd
destination:
  server: 'https://kubernetes.default.svc'
  namespace: argocd
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
